//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.17 at 06:25:15 PM CEST 
//


package xml.projekat.com.javageneratedfiles;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.projekat.com.javageneratedfiles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.projekat.com.javageneratedfiles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Advertisement }
     * 
     */
    public Advertisement createAdvertisement() {
        return new Advertisement();
    }

    /**
     * Create an instance of {@link GetAdvertisementRequest }
     * 
     */
    public GetAdvertisementRequest createGetAdvertisementRequest() {
        return new GetAdvertisementRequest();
    }

    /**
     * Create an instance of {@link GetAdvertisementResponse }
     * 
     */
    public GetAdvertisementResponse createGetAdvertisementResponse() {
        return new GetAdvertisementResponse();
    }

    /**
     * Create an instance of {@link Advertisement.Brand }
     * 
     */
    public Advertisement.Brand createAdvertisementBrand() {
        return new Advertisement.Brand();
    }

    /**
     * Create an instance of {@link Advertisement.CarClass }
     * 
     */
    public Advertisement.CarClass createAdvertisementCarClass() {
        return new Advertisement.CarClass();
    }

    /**
     * Create an instance of {@link Advertisement.FuelType }
     * 
     */
    public Advertisement.FuelType createAdvertisementFuelType() {
        return new Advertisement.FuelType();
    }

    /**
     * Create an instance of {@link Advertisement.Model }
     * 
     */
    public Advertisement.Model createAdvertisementModel() {
        return new Advertisement.Model();
    }

    /**
     * Create an instance of {@link Advertisement.TransType }
     * 
     */
    public Advertisement.TransType createAdvertisementTransType() {
        return new Advertisement.TransType();
    }

}
